### ISSUE TITLE
Migrate to the new developer api

### ISSUE THREAD

**Issue by avivbiton** [avivbiton/BlizzardApiReader#35]
Blizzard launched new api portal.
https://develop.battle.net/documentation/guides/migration-guide

**Comment by linahanner** [comment]
The old API portal will work until January 6th in 2019 for anyone in possession of an API key. From my understanding it will not be possible to create a new API key if you don't already have one.

The real difference between the old and new API portals is the new portal requires OAuth authentication. This will require a Client ID and Client Secret. We could add an option to the ApiConfiguration for the time being which allows the user to use OAuth will all necessary values such as redirect uri, scopes & etc. Depending on this value the Reader will choose to either retrieve tokens when appropriate (OAuth) or use the API key. And then we can force it to OAuth at January 6th and forward.

We also need to implement an OAuth flow, which might potentially mean requiring a database in order to store user-specific access tokens.

**Comment by avivbiton** [comment]
Working on this, my issue right now is that I am getting authentication error when requesting an access token. Will look into more of this, if you have useful info on how to do the authentication correctly please tell me.

**Comment by linahanner** [comment]
Note the following:
- The request must be done using HTTPS (e.g. https://us.battle.net/oauth/token)
- The body must contain the key grant_type with value client_credentials
- The Content-Type of the body has to be x-www-form-urlencoded as per the standards of OAuth 2.0
- The client id and client secret needs to be passed as Basic authentication where the id represents the username and the secret the password (see [Basic authentication](https://en.wikipedia.org/wiki/Basic_access_authentication))

**Comment by avivbiton** [comment]
Yeah, I managed to get that working. Will finish it soon (hopefully)

**Comment by avivbiton** [comment]
#38
